#spring:
#  datasource:
#    url: jdbc:mysql://uh8m7ouzoyebxndv:CwxkT4yTo9RnftpEZ3ua@bculpvewq1aw2twkdqe2-mysql.services.clever-cloud.com:3306/bculpvewq1aw2twkdqe2
#    username: uh8m7ouzoyebxndv
#    password: CwxkT4yTo9RnftpEZ3ua
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL57Dialect
#    hibernate:
#      ddl-auto: update
#app:
#  jwtCookieName: em
#  jwtSecret: AsD123a
#  jwtExpirationMs: 86400000