spring:
  datasource:
    url: jdbc:mysql://localhost/argprograma_backend?useSSL=false
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL57Dialect
#    hibernate:
#      ddl-auto: update
app:
  jwtCookieName: em
  jwtSecret: AsD123a
  jwtExpirationMs: 86400000